In [ ]:
import numpy as np
import pandas as pd

In [ ]:
label = ['a','b','c']
lis = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [ ]:
pd.Series(lis,index=label)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

In [ ]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [ ]:
df['Designation'] = ["Doctor","Eng.","Doctor","Eng."]
df

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [ ]:
df = df.drop('Designation',axis = 1)

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.drop('Age',axis=1,inplace=True)

In [ ]:
df

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000
3  Linda    London   85000

In [ ]:
df.loc[1]

Name       Anna
City      Paris
Salary    70000
Name: 1, dtype: object

In [ ]:
df[df['Salary'] >= 65000]

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
3  Linda    London   85000

## Missing Data

In [ ]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
dt = pd.DataFrame(data)
dt

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
dt.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:
dt.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
dt.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000
3  Linda    London   85000

In [ ]:
dt.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [ ]:
dt.fillna(0,inplace=True)

In [ ]:
dt

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
dt.fillna(dt.mean(),inplace=True)

In [ ]:
dt

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [ ]:
df.shape

(4, 3)

In [ ]:
df.columns

Index(['Name', 'City', 'Salary'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   City    4 non-null      object
 2   Salary  4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

             Salary
count      4.000000
mean   70500.000000
std    10214.368964
min    62000.000000
25%    64250.000000
50%    67500.000000
75%    73750.000000
max    85000.000000

In [ ]:
def sq(x):
  return x**2

In [ ]:
df['sq_sal'] = df['Salary'].apply(sq)

In [ ]:
df

    Name      City  Salary      sq_sal
0   John  New York   65000  4225000000
1   Anna     Paris   70000  4900000000
2  Peter    Berlin   62000  3844000000
3  Linda    London   85000  7225000000

In [52]:
df = pd.read_csv('/content/ML/anime.csv')
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [53]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [57]:
def ex_episode(txt):
  data = ""
  ok = False
  for i in txt:
    if i == ')':
      return data
    if ok:
      data += i
    if i == '(':
      ok = True
  return data

In [58]:
df["Episode"] = df["Title"].apply(ex_episode)

In [59]:
df["Episode"]

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Episode, dtype: object

In [61]:
df.head()

   Rank                                              Title  Score Episode
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10  64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07  24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06  13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06  51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05  10 eps