In [1]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
import pandas as pd
health = {
    "height" : [5.5,5.5,6.0,5.8],
    "weight" : [57,62,72,75],
    "bmi" : [19.3,12.7,20.3,None],
    "smoker":["Yes","No",None,"Yes"]
}
health["height"]

[5.5, 5.5, 6.0, 5.8]

In [21]:
health_data_frame = pd.DataFrame(
    health)
print(type(health))
print(type(health_data_frame))

<class 'dict'>
<class 'pandas.DataFrame'>

In [22]:
health_data_frame.head()

   height  weight   bmi smoker
0     5.5      57  19.3    Yes
1     5.5      62  12.7     No
2     6.0      72  20.3    NaN
3     5.8      75   NaN    Yes

In [23]:
health_data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   height  4 non-null      float64
 1   weight  4 non-null      int64
 2   bmi     3 non-null      float64
 3   smoker  3 non-null      str
dtypes: float64(2), int64(1), str(1)
memory usage: 260.0 bytes

In [24]:
health_data_frame.describe()

         height    weight        bmi
count  4.000000   4.00000   3.000000
mean   5.700000  66.50000  17.433333
std    0.244949   8.42615   4.129568
min    5.500000  57.00000  12.700000
25%    5.500000  60.75000  16.000000
50%    5.650000  67.00000  19.300000
75%    5.850000  72.75000  19.800000
max    6.000000  75.00000  20.300000

In [26]:
health_data_frame.to_csv("G:\\ML\\Numpy\\Python_\\data.csv")

In [28]:
data = pd.read_csv("G:\\ML\\Numpy\\Python_\\data2.csv")
data.head()

   height  weight   bmi smoker
0     5.5      57  19.3    Yes
1     5.5      62  12.7     No
2     6.0      72  20.3    NaN
3     5.8      75   NaN    Yes

In [37]:
sort_data = data.sort_values(
    by=['height','bmi'],
    ascending=[False,False]
)
sort_data.head()

   height  weight   bmi smoker
2     6.0      72  20.3    NaN
3     5.8      75   NaN    Yes
0     5.5      57  19.3    Yes
1     5.5      62  12.7     No

In [40]:
new_d = sort_data[['height','bmi']]
new_d.head()

   height   bmi
2     6.0  20.3
3     5.8   NaN
0     5.5  19.3
1     5.5  12.7

In [45]:
mask = data['height'] == 5.5
print(mask)
data[mask]

0     True
1     True
2    False
3    False
Name: height, dtype: bool

   height  weight   bmi smoker
0     5.5      57  19.3    Yes
1     5.5      62  12.7     No

In [49]:
new_da = data.query(
    "height == 5.5 and smoker == 'Yes'"
)
new_da.head()

   height  weight   bmi smoker
0     5.5      57  19.3    Yes

In [51]:
import os
root_dir = "G:\\ML\\Numpy"
data_dir = os.path.join(root_dir,'Python_')
dataset_path = os.path.join(data_dir,'data2.csv')
print(dataset_path)

G:\ML\Numpy\Python_\data2.csv

In [53]:
sales = pd.read_csv(dataset_path)
sales.head()

   height  weight   bmi smoker
0     5.5      57  19.3    Yes
1     5.5      62  12.7     No
2     6.0      72  20.3    NaN
3     5.8      75   NaN    Yes

In [54]:
sales = sales.drop(columns = ['smoker'])
sales.head()

   height  weight   bmi
0     5.5      57  19.3
1     5.5      62  12.7
2     6.0      72  20.3
3     5.8      75   NaN

In [55]:
def normalize(col):
    mean = col.mean()
    std = col.std()
    return (col - mean) / std

In [58]:
normalize(sales['weight'])

0   -1.127443
1   -0.534052
2    0.652730
3    1.008764
Name: weight, dtype: float64

In [59]:
import numpy as np
apply_two_col = sales[['height','weight']].agg([normalize,np.cumsum])
apply_two_col

     height           weight
  normalize cumsum normalize cumsum
0 -0.816497    5.5 -1.127443     57
1 -0.816497   11.0 -0.534052    119
2  1.224745   17.0  0.652730    191
3  0.408248   22.8  1.008764    266

In [2]:
import pandas as pd
health = {
    "height" : [5.5,5.5,6.0,5.8],
    "weight" : [57,62,72,75],
    "bmi" : [19.3,12.7,20.3,None],
    "smoker":["Yes","No",None,"Yes"]
}
health["height"]

[5.5, 5.5, 6.0, 5.8]

In [3]:
health_data_frame = pd.DataFrame(
    health)
print(type(health))
print(type(health_data_frame))

<class 'dict'>
<class 'pandas.DataFrame'>

In [2]:
cur = health_data_frame.pivot_table(
    values=['height','weight'],
    index='smoker',
    aggfun=[min,max]
)
cur.head()

NameError: name 'health_data_frame' is not defined