In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr*5)

[ 5 10 15 20]

In [2]:
import pandas as pd
import numpy as np

data = {
    'Duration': [60, 60, 60, 45, 45, 60, 60, 450, 30, 60, 60, 60, 60, 60, 60, 60, 60, 45, 60, 45, 60, 60, 45, 60, 45, 60, 60, 60, 60, 60, 60, 60, 60],
    'Date': ['2023/12/01', '2023/12/02', '2023/12/03', '2023/12/04', np.nan, '2023/12/06', '2023/12/07', '2023/12/08', '2023/12/09', '2023/12/10', '2023/12/11', '2023/12/12', '2023/12/12', '2023/12/14', '2023/12/15', '2023/12/16', '2023/12/17', '2023/12/18', '2023/12/19', '2023/12/20', '2023/12/21', '2023/12/22', '2023/12/23', '2023/12/24', '2023/12/25', '2023/12/26', '2023/12/27', '2023/12/28', '2023/12/29', '2023/12/30', '2023/12/31', '2024/01/01', '2024/01/02'],
    'Pulse': [110, 117, 103, 109, 117, 102, 110, 104, 109, 98, 103, 100, 100, 106, 104, 98, 98, 100, 103, 100, 108, 100, 102, 110, 110, 115, 120, 103, 100, 102, 92, 110, 110],
    'Maxpulse': [130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 120, 128, 132, 123, 120, 120, 123, 125, 131, 119, 126, 133, 128, 144, 150, 123, 120, 129, 115, 130, 130]
}

health_monitor_data = pd.DataFrame(data)

# This will now match your screenshot's structure
print(health_monitor_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
dtypes: int64(3), str(1)
memory usage: 1.2 KB
None

In [3]:
health_monitor_data.to_csv('health_data.csv', index=False)

In [12]:
import os
root_dir = "G:\\ML\\Numpy"
data_dir = os.path.join(root_dir,"Python_")
data_set_path =  os.path.join(data_dir,"health_monitor_full.csv")

In [13]:
health_monitor_data = pd.read_csv(data_set_path)
health_monitor_data.head()

   Duration          Date  Pulse  Maxpulse  Calories      Type
0        60  '2020/12/01'    110       130     409.1      Easy
1        60  '2020/12/02'    117       145     479.0  Moderate
2        60  '2020/12/03'    103       135     340.0  Moderate
3        45  '2020/12/04'    109       175     282.4  Moderate
4        45           NaN    117       148     406.0     Heavy

In [9]:

data = {
    'Duration': [60, 60, 60, 45, 45, 60, 60, 450, 30, 60, 60, 60, 60, 60, 60, 60, 60, 45, 60, 45, 60, 60, 45, 60, 45, 60, 60, 60, 60, 60, 60, 60, 60],
    # Index 4 is set to None/NaN to match your 32 non-null count
    'Date': ["'2020/12/01'", "'2020/12/02'", "'2020/12/03'", "'2020/12/04'", None, "'2020/12/06'", "'2020/12/07'", "'2020/12/08'", "'2020/12/09'", "'2020/12/10'", "'2020/12/11'", "'2020/12/12'", "'2020/12/12'", "'2020/12/14'", "'2020/12/15'", "'2020/12/16'", "'2020/12/17'", "'2020/12/18'", "'2020/12/19'", "'2020/12/20'", "'2020/12/21'", "'2020/12/22'", "'2020/12/23'", "'2020/12/24'", "'2020/12/25'", "'2020/12/26'", "'2020/12/27'", "'2020/12/28'", "'2020/12/29'", "'2020/12/30'", "'2020/12/31'", "'2021/01/01'", "'2021/01/02'"],
    'Pulse': [110, 117, 103, 109, 117, 102, 110, 104, 109, 98, 103, 100, 100, 106, 104, 98, 98, 100, 103, 100, 108, 100, 102, 110, 110, 115, 120, 103, 100, 102, 92, 110, 110],
    'Maxpulse': [130, 145, 135, 175, 148, 127, 136, 134, 133, 124, 147, 120, 120, 128, 132, 123, 120, 120, 123, 125, 131, 119, 126, 133, 128, 144, 150, 123, 120, 129, 115, 130, 130],
    'Calories': [409.1, 479.0, 340.0, 282.4, 406.0, 300.5, 374.0, 253.3, 195.1, 269.0, 329.3, 250.7, 250.7, 345.3, 379.3, 275.0, 215.2, 300.0, 323.0, 243.0, 364.2, 282.0, 300.0, 370.0, 270.8, 382.0, 420.2, 320.4, 280.9, 342.0, 230.1, 380.0, 390.0],
    'Type': ['Easy', 'Moderate', 'Moderate', 'Moderate', 'Heavy', 'Easy', 'Moderate', 'Heavy', 'Easy', 'Moderate', 'Moderate', 'Easy', 'Easy', 'Moderate', 'Heavy', 'Easy', 'Easy', 'Moderate', 'Moderate', 'Easy', 'Moderate', 'Easy', 'Moderate', 'Moderate', 'Easy', 'Heavy', 'Heavy', 'Moderate', 'Easy', 'Moderate', 'Easy', 'Moderate', 'Moderate']
}

health_monitor_data = pd.DataFrame(data)

# Save to CSV (without the index column)
health_monitor_data.to_csv('health_monitor_full.csv', index=False)

# Verify the structure matches your first image
print(health_monitor_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  33 non-null     float64
 5   Type      33 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB
None

In [15]:
health_monitor_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  33 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     33 non-null     int64
 3   Maxpulse  33 non-null     int64
 4   Calories  33 non-null     float64
 5   Type      33 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [16]:
health_monitor_data["Type"].value_counts()

Type
Moderate    16
Easy        12
Heavy        5
Name: count, dtype: int64

In [18]:
mask = health_monitor_data.isnull().any(axis = 1)
print(mask)

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
dtype: bool

In [19]:
health_monitor_data[mask]

   Duration Date  Pulse  Maxpulse  Calories   Type
4        45  NaN    117       148     406.0  Heavy

In [20]:
health_monitor_data = health_monitor_data.dropna()
health_monitor_data.info()

<class 'pandas.DataFrame'>
Index: 32 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
 5   Type      32 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.8 KB

In [21]:
mask = health_monitor_data.duplicated()
print(mask)
health_monitor_data[mask]

0     False
1     False
2     False
3     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
dtype: bool

    Duration          Date  Pulse  Maxpulse  Calories  Type
12        60  '2020/12/12'    100       120     250.7  Easy

In [22]:
health_monitor_data = health_monitor_data.drop_duplicates()

In [24]:
print(health_monitor_data.duplicated().sum())

0

In [25]:
health_monitor_data.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: float64(1), int64(3), str(2)
memory usage: 1.7 KB

In [26]:
health_monitor_data['Date'] = health_monitor_data['Date'].astype('datetime64[ns]')
health_monitor_data.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 32
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
 5   Type      31 non-null     str
dtypes: datetime64[ns](1), float64(1), int64(3), str(1)
memory usage: 1.7 KB

In [27]:
health_monitor_data.describe()

,Duration,Date,Pulse,Maxpulse,Calories
count,31.000000,31,31.000000,31.000000,31.000000
mean,69.193548,2020-12-17 12:23:13.548387072,105.032258,130.806452,319.219355
min,30.000000,2020-12-01 00:00:00,92.000000,115.000000,195.100000
25%,60.000000,2020-12-09 12:00:00,100.000000,123.000000,272.900000
50%,60.000000,2020-12-18 00:00:00,103.000000,129.000000,320.400000
75%,60.000000,2020-12-25 12:00:00,110.000000,133.500000,372.000000
max,450.000000,2021-01-02 00:00:00,120.000000,175.000000,479.000000
std,71.064487,NaN,6.183224,11.836157,65.967095

In [29]:
Q1 = health_monitor_data['Pulse'].quantile(0.25)
print(Q1)
Q3 =  health_monitor_data['Pulse'].quantile(0.75)
print(Q3)
IQR = Q3 - Q1
L = Q1 - 1.5 * IQR
R = Q3 + 1.5 * IQR
print(L,R)

100.0
110.0
85.0 125.0

In [30]:
non_out_mask = health_monitor_data['Pulse'].between(L,R)
out_mask = ~non_out_mask
health_monitor_data[out_mask]

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories, Type]
Index: []

In [31]:
health_monitor_data.describe()

,Duration,Date,Pulse,Maxpulse,Calories
count,31.000000,31,31.000000,31.000000,31.000000
mean,69.193548,2020-12-17 12:23:13.548387072,105.032258,130.806452,319.219355
min,30.000000,2020-12-01 00:00:00,92.000000,115.000000,195.100000
25%,60.000000,2020-12-09 12:00:00,100.000000,123.000000,272.900000
50%,60.000000,2020-12-18 00:00:00,103.000000,129.000000,320.400000
75%,60.000000,2020-12-25 12:00:00,110.000000,133.500000,372.000000
max,450.000000,2021-01-02 00:00:00,120.000000,175.000000,479.000000
std,71.064487,NaN,6.183224,11.836157,65.967095

In [32]:
health_monitor_data = health_monitor_data.drop(columns = ['Date'])
health_monitor_data.info()

<class 'pandas.DataFrame'>
Index: 31 entries, 0 to 32
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Pulse     31 non-null     int64
 2   Maxpulse  31 non-null     int64
 3   Calories  31 non-null     float64
 4   Type      31 non-null     str
dtypes: float64(1), int64(3), str(1)
memory usage: 1.5 KB

In [33]:
def normalize(col):
    mean = col.mean()
    std = col.std()
    return (col - mean) / std

health_monitor_data['Duration'] = health_monitor_data['Duration'].agg(normalize)
health_monitor_data['Pulse'] = health_monitor_data['Pulse'].agg(normalize)
health_monitor_data['Maxpulse'] = health_monitor_data['Maxpulse'].agg(normalize)
health_monitor_data['Calories'] = health_monitor_data['Calories'].agg(normalize)
health_monitor_data.head()

   Duration     Pulse  Maxpulse  Calories      Type
0 -0.129369  0.803423 -0.068135  1.362507      Easy
1 -0.129369  1.935518  1.199169  2.422126  Moderate
2 -0.129369 -0.328673  0.354300  0.315015  Moderate
3 -0.340445  0.641695  3.733775 -0.558147  Moderate
5 -0.129369 -0.490401 -0.321595 -0.283768      Easy

In [34]:
health_monitor_data_one_hot_encoded = pd.get_dummies(
    health_monitor_data,
    columns = ['Type'],
    sparse = True
)
health_monitor_data_one_hot_encoded.head()

,Duration,Pulse,Maxpulse,Calories,Type_Easy,Type_Heavy,Type_Moderate
0,-0.129369,0.803423,-0.068135,1.362507,True,False,False
1,-0.129369,1.935518,1.199169,2.422126,False,False,True
2,-0.129369,-0.328673,0.354300,0.315015,False,False,True
3,-0.340445,0.641695,3.733775,-0.558147,False,False,True
5,-0.129369,-0.490401,-0.321595,-0.283768,True,False,False

In [38]:
health_monitor_data['label_encoded_type'] = pd.Categorical(
     health_monitor_data['Type'],
     categories=['Easy','Moderate','Heavy'],
     ordered = True
 ).codes
health_monitor_data.head()

   Duration     Pulse  Maxpulse  Calories      Type  label_encoded_type
0 -0.129369  0.803423 -0.068135  1.362507      Easy                   0
1 -0.129369  1.935518  1.199169  2.422126  Moderate                   1
2 -0.129369 -0.328673  0.354300  0.315015  Moderate                   1
3 -0.340445  0.641695  3.733775 -0.558147  Moderate                   1
5 -0.129369 -0.490401 -0.321595 -0.283768      Easy                   0